# Generated by Django 5.2.8 on 2026-01-22 07:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FIMConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scan_mode', models.CharField(choices=[('realtime', 'Real-time Monitoring'), ('scheduled', 'Scheduled Scans'), ('hybrid', 'Hybrid (Real-time + Scheduled)')], default='realtime', help_text='Monitoring mode', max_length=20)),
                ('schedule_interval', models.IntegerField(default=300, help_text='Scan interval in seconds for scheduled mode')),
                ('alert_on_add', models.BooleanField(default=True)),
                ('alert_on_modify', models.BooleanField(default=True)),
                ('alert_on_delete', models.BooleanField(default=True)),
                ('hash_algorithm', models.CharField(choices=[('md5', 'MD5'), ('sha1', 'SHA-1'), ('sha256', 'SHA-256'), ('sha512', 'SHA-512')], default='sha256', max_length=20)),
                ('max_file_size', models.BigIntegerField(default=104857600, help_text='Maximum file size to hash (in bytes)')),
                ('exclusion_patterns', models.TextField(blank=True, help_text='Comma-separated list of exclusion patterns')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, help_text='User ID (stored as integer since users are in auth database)', null=True)),
            ],
            options={
                'verbose_name': 'FIM Configuration',
                'verbose_name_plural': 'FIM Configurations',
                'db_table': 'fim_configurations',
            },
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(help_text='Full path to the directory being monitored', max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether monitoring is active')),
                ('last_scan', models.DateTimeField(blank=True, help_text='Last scan timestamp', null=True)),
                ('recursive', models.BooleanField(default=True, help_text='Monitor subdirectories recursively')),
                ('scan_interval', models.IntegerField(default=300, help_text='Scan interval in seconds')),
            ],
            options={
                'verbose_name': 'Directory',
                'verbose_name_plural': 'Directories',
                'db_table': 'directories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['path'], name='directories_path_f48ed4_idx'), models.Index(fields=['is_active'], name='directories_is_acti_024a21_idx'), models.Index(fields=['created_at'], name='directories_created_e2161c_idx')],
            },
        ),
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_path', models.CharField(db_index=True, help_text='Relative path from the monitored directory', max_length=500)),
                ('item_type', models.CharField(choices=[('file', 'File'), ('directory', 'Directory'), ('symlink', 'Symbolic Link'), ('other', 'Other')], default='file', help_text='Type of file system item', max_length=10)),
                ('hash', models.CharField(blank=True, help_text='SHA-256 hash of file content', max_length=128, null=True, validators=[django.core.validators.MinLengthValidator(32)])),
                ('size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('permissions', models.CharField(blank=True, help_text="File permissions (e.g., 'rw-r--r--')", max_length=10, null=True)),
                ('owner', models.CharField(blank=True, help_text='File owner', max_length=100, null=True)),
                ('group', models.CharField(blank=True, help_text='File group', max_length=100, null=True)),
                ('last_modified', models.DateTimeField(help_text='Last modification time from filesystem')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('detected_at', models.DateTimeField(auto_now_add=True, help_text='When this change was detected')),
                ('status', models.CharField(choices=[('current', 'Current - Baseline'), ('added', 'Added - New File'), ('modified', 'Modified - Changed'), ('deleted', 'Deleted - Removed'), ('renamed', 'Renamed - Moved/Renamed')], db_index=True, default='current', help_text='Current status of the file', max_length=50)),
                ('previous_hash', models.CharField(blank=True, help_text='Previous hash before modification', max_length=128, null=True)),
                ('change_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this change event', unique=True)),
                ('reported', models.BooleanField(default=False, help_text='Whether this change has been reported')),
                ('restored', models.BooleanField(default=False, help_text='Whether this file has been restored from backup')),
                ('directory', models.ForeignKey(help_text='Directory containing this file', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='fim.directory')),
            ],
            options={
                'verbose_name': 'File Metadata',
                'verbose_name_plural': 'File Metadata',
                'db_table': 'file_metadata',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('backup_type', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('restore', 'Restore Point')], max_length=20)),
                ('original_path', models.CharField(max_length=500)),
                ('backup_path', models.CharField(max_length=500)),
                ('hash', models.CharField(max_length=128)),
                ('size', models.BigIntegerField()),
                ('backed_up_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('backed_up_by', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('restored', models.BooleanField(default=False)),
                ('restore_count', models.IntegerField(default=0)),
                ('file_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='fim.filemetadata')),
            ],
            options={
                'verbose_name': 'Backup Record',
                'verbose_name_plural': 'Backup Records',
                'db_table': 'backup_records',
                'ordering': ['-backed_up_at'],
            },
        ),
        migrations.CreateModel(
            name='FIMLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('scan', 'Scan'), ('change', 'Change Detection'), ('alert', 'Alert'), ('system', 'System'), ('backup', 'Backup'), ('restore', 'Restore')], max_length=20)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='fim.directory')),
                ('file_metadata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='fim.filemetadata')),
            ],
            options={
                'verbose_name': 'FIM Log',
                'verbose_name_plural': 'FIM Logs',
                'db_table': 'fim_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExclusionPattern',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pattern', models.CharField(max_length=500)),
                ('pattern_type', models.CharField(choices=[('glob', 'Glob Pattern'), ('regex', 'Regular Expression'), ('extension', 'File Extension'), ('path', 'Path Contains')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_global', models.BooleanField(default=False, help_text='Apply to all directories')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='fim.directory')),
            ],
            options={
                'verbose_name': 'Exclusion Pattern',
                'verbose_name_plural': 'Exclusion Patterns',
                'db_table': 'exclusion_patterns',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_global'], name='exclusion_p_is_glob_1eda8e_idx'), models.Index(fields=['is_active'], name='exclusion_p_is_acti_3d047d_idx'), models.Index(fields=['directory', 'is_active'], name='exclusion_p_directo_e427d0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='filemetadata',
            index=models.Index(fields=['status'], name='file_metada_status_a4801c_idx'),
        ),
        migrations.AddIndex(
            model_name='filemetadata',
            index=models.Index(fields=['detected_at'], name='file_metada_detecte_f2a264_idx'),
        ),
        migrations.AddIndex(
            model_name='filemetadata',
            index=models.Index(fields=['directory', 'item_path'], name='file_metada_directo_bdb770_idx'),
        ),
        migrations.AddIndex(
            model_name='filemetadata',
            index=models.Index(fields=['directory', 'status'], name='file_metada_directo_44ea68_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filemetadata',
            unique_together={('directory', 'item_path', 'status')},
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['backed_up_at'], name='backup_reco_backed__346cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['original_path'], name='backup_reco_origina_129129_idx'),
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['file_metadata'], name='backup_reco_file_me_932dac_idx'),
        ),
        migrations.AddIndex(
            model_name='fimlog',
            index=models.Index(fields=['timestamp'], name='fim_logs_timesta_8c6abc_idx'),
        ),
        migrations.AddIndex(
            model_name='fimlog',
            index=models.Index(fields=['log_type', 'level'], name='fim_logs_log_typ_79fdd2_idx'),
        ),
        migrations.AddIndex(
            model_name='fimlog',
            index=models.Index(fields=['directory', 'timestamp'], name='fim_logs_directo_22b8e3_idx'),
        ),
    ]
