# Generated by Django 5.2.8 on 2026-02-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('interface', models.CharField(max_length=50)),
                ('total_packets', models.BigIntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('bandwidth_mbps', models.FloatField(default=0.0)),
                ('packet_types', models.JSONField(default=dict)),
                ('uptime_seconds', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NetworkAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField()),
                ('packet_data', models.JSONField(blank=True, default=dict, null=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='NTA_network_timesta_dd52e9_idx'), models.Index(fields=['severity'], name='NTA_network_severit_015b08_idx')],
            },
        ),
    ]
